language: node_js

node_js:
  - "node"

after_success:
  - git config --global user.name "aswinavofficial"
  - git config --global user.email "aswinavofficial@gmail.com"
  - git remote rm origin
  - git remote add origin https://aswinavofficial:${GH_TOKEN}@github.com/aswinavofficial/instagram-clone.git
  - npm run deploy

env:
    process.env.CI : false
    process.env.REACT_APP_SERVICE_URI : "https://insta-server.aswin.tech"
